spring:
  application:
    name: ZooKeeperTest
  cloud:
    zookeeper:
      connect-string: localhost:2181
      discovery:
        enabled: true
      dependencies:
        dependencyOne:
          path: ZooKeeperTest
logging:
  level:
    org.apache.zookeeper.ClientCnxn: WARN